# This is the main configuration file of your Dancer app
# env-related settings should go to environments/$env.yml.
# All the settings in this file will be loaded at Dancer's startup.

# Your application's name
appname: "Word::Partition"

# The default layout to use for your application (located in
# views/layouts/main.tt)
layout: "main"

# When the charset is set to UTF-8 Dancer will handle for you
# all the magic of encoding and decoding. You should not care
# about unicode within your app when this setting is set (recommended).
charset: "UTF-8"

# template engine
# simple: default and very basic template engine
# template_toolkit: TT

#template: "simple"

template: "template_toolkit"
# engines:
#   template_toolkit:
#     start_tag: '[%'
#     end_tag:   '%]'

# For session support enable the following line and see Dancer::Session
session: "YAML"

plugins:
  Database:
        driver: 'mysql'
        database: 'word_part'
        host: 'localhost'
        port: 3306
        username: 'root'
        password: 'abc123'
        connection_check_threshold: 10
        dbi_params:
            RaiseError: 1
            AutoCommit: 1
        on_connect_do: ["SET NAMES 'utf8'", "SET CHARACTER SET 'utf8'" ]
        log_queries: 1
  DBIC:
    "word_part":
        schema_class: Word::Partition::Schema
        dsn: "dbi:mysql:database=word_part"
        user: 'root'
        password: 'abc123'
  Auth::Extensible:
        exit_page: '/'
        login_page_handler: 'Word::Partition::login_page_handler'
        realms:
            users:
                provider: 'Database'
                # optionally set DB connection name to use (see named 
                # connections in Dancer::Plugin::Database docs)
#                db_connection_name: 'foo'

                # Optionally disable roles support, if you only want to check
                # for successful logins but don't need to use role-based access:
                disable_roles: 1
                # After /logout land here ('/' is default)

                # optionally specify names of tables if they're not the defaults
                # (defaults are 'users', 'roles' and 'user_roles')
                users_table: 'api_access'
#                roles_table: 'roles'
#                user_roles_table: 'user_roles'

                # optionally set the column names (see the SUGGESTED SCHEMA
                # section below for the default names; if you use them, they'll
                # Just Work)
                users_id_column: 'id'
                users_username_column: 'username'
                users_password_column: 'token'
#                roles_id_column: 'id'
#                roles_role_column: 'role'
#                user_roles_user_id_column: 'user_id'
#                user_roles_role_id_column: 'roles_id'
