appname: "Word::Partition"

layout: "main"

charset: "UTF-8"

template: "template_toolkit"

session: "YAML"

plugins:
  Database:
        driver: 'sqlite'
        database: 'word_part'
        host: 'localhost'
        username: ''
        password: ''
        connection_check_threshold: 10
        dbi_params:
            RaiseError: 1
            AutoCommit: 1
        on_connect_do: ["SET NAMES 'utf8'", "SET CHARACTER SET 'utf8'" ]
        log_queries: 1
  DBIC:
    "word_part":
        schema_class: Word::Partition::Schema
        dsn: "dbi:SQLite:dbname=word_part.db"
        user: ''
        password: ''
  Auth::Extensible:
        exit_page: '/'
        login_page_handler: 'Word::Partition::_login_page_handler'
        realms:
            users:
                provider: 'Database'
                disable_roles: 1
                users_table: 'api_access'
                users_id_column: 'id'
                users_username_column: 'username'
                users_password_column: 'token'
