package WordPart;

=head1 Word-part Manipulation

=item Database manipulation of word-part fragments

=item Scoring combinations of parsed and defined terminology

=item Web GUI interaction

=head1 Data Model

Used L<DBIx::Class::Schema::Loader|https://metacpan.org/release/DBIx-Class-Schema-Loader> for my existing database

=begin text

 affix       definition              etymology
 ---------------------------------------------
 ab          from, away              latin
 bio         life                    greek
 o           combining               NULL
 ortho       straight, right angles  greek
 phile?      loving, thriving        greek
 ic          belonging               greek
 ...

=end text

L<"biophilic" - belonging to things that thrive on life|http://localhost:5000/parse?query=biophilic>

=head1 Routes: Verbs & Behaviors

=begin html

<img src="pix/railroad.jpg" style="float:right" />

=end html

=over 4

=item B<get>

Direct to index

Show search, edit and parse forms

Delete a record (anchor)

=item B<post>

Add a record

Update a record

=back

=head1 Authorization

Using L<Dancer::Plugin::Auth::Extensible|https://metacpan.org/pod/Dancer::Plugin::Auth::Extensible>

=begin text

 get '/parse' => require_login sub { ...

=end text

Provides <code>/login</code> and <code>/logout</code> routes

Configured in the <code>config.yml</code> file

=head1 Search by Affix or Definition

Using L<Dancer::Plugin::DBIC|https://metacpan.org/pod/Dancer::Plugin::DBIC>
and L<Dancer::Plugin::Database|https://metacpan.org/pod/Dancer::Plugin::Database>

=begin text

 get '/search' => require_login sub {
    ...
    my $type = params->{type};
    $type //= 'affix';  # Option via form: 'definition'
    ...
    my $fragments = $schema->resultset('Fragment')->search(
        {
            $type => { like => "%$like%" },
        },
        {
            order_by => { -asc => 'affix' }
        }
    );
    ...
 }

=end text

=head1 Post by ID or Database Columns

=begin text

 post '/update' => require_login sub {
    my $fragment = $schema->resultset('Fragment')->find(
        {
            id => params->{id}
        }
    );
    ...
 }

=end text

=for html

<p/>

=end html

=begin text

 post '/add' => require_login sub {
    ...
    $schema->resultset('Fragment')->create(
        {
            affix      => $affix,
            definition => params->{definition},
            etymology  => params->{etymology},
        }
    );
    ...
 };

=end text

=head1 New/Edit Template

=begin text

 <form action="/<% method %>" method="post">
     ...
     <input name="affix" type="text" value="<% affix %>" autofocus />
     ...
     <input name="prefix" type="checkbox"><label for="prefix">Prefix</label>
     <input name="suffix" type="checkbox"><label for="suffix">Suffix</label>
     ...
     <select name="etymology">
         <option value="">Choose a language...</option>
         <option value="greek" <% etymology == "greek" ? "selected" : "" %>>Greek</option>
     ...
     <input name="definition" type="text" value="<% definition %>" />
     ...
     <input type="submit" name="<% method %>" value="<% method FILTER ucfirst %>" class="small round button" />
     ...
     <% IF id %>
         <a href="/delete?id=<% id %>" class="small round button" onclick="return confirm('Delete <% affix %>?')">Delete</a>
     <% END %>
 </form>

=end text

=head1 Parse a Word

Break a word into known parts with
L<Lingua::Word::Parser|https://metacpan.org/release/Lingua-Word-Parser>

=begin text

 get '/parse' => require_login sub {
    ...
    if ( $query ) {
        my $p = Lingua::Word::Parser->new(
            word   => $query,
            dbname => config->{plugins}{Database}{database},
            dbuser => config->{plugins}{Database}{username},
            dbpass => config->{plugins}{Database}{password},
            dbtype => config->{plugins}{Database}{driver},
            dbhost => config->{plugins}{Database}{host},
        );
        $p->knowns;
        $p->power;
        my $score = $p->score( '[', ']' );
        ...
 }

=end text

=head1 Build a Term

=begin html

<img src="pix/blueprint.jpg" style="float:right" />

=end html

Currently this is a manual process of looking up possible affixes by
definition, then stitching them together, by hand.

=head1 Links

The code behind this presentation:

L<Word-Part|https://github.com/ology/Word-Part>
on github

L<Lingua::Word::Parser|https://metacpan.org/release/Lingua-Word-Parser>
on CPAN

L<Pod::S5|https://metacpan.org/release/Pod-S5>
on CPAN

=cut

1;
__END__
:!pod2s5 --theme yatil --name "Gene Boggs" %
